// database.js - Blocco 1 (20 Squadre)
const playerDatabase = [
    // --- LE GRANDI STORICHE ---
    
    // JUVENTUS 2014/15
    { name: "G. Buffon", team: "Juventus", era: "14/15", ovr: 95, roles: ["POR"] },
    { name: "L. Bonucci", team: "Juventus", era: "14/15", ovr: 89, roles: ["DC"] },
    { name: "G. Chiellini", team: "Juventus", era: "14/15", ovr: 90, roles: ["DC", "TS"] },
    { name: "A. Barzagli", team: "Juventus", era: "14/15", ovr: 88, roles: ["DC", "TD"] },
    { name: "S. Lichtsteiner", team: "Juventus", era: "14/15", ovr: 84, roles: ["TD", "ED"] },
    { name: "P. Evra", team: "Juventus", era: "14/15", ovr: 83, roles: ["TS", "ES"] },
    { name: "A. Pirlo", team: "Juventus", era: "14/15", ovr: 90, roles: ["CC", "MED"] },
    { name: "P. Pogba", team: "Juventus", era: "14/15", ovr: 91, roles: ["CC", "TRQ", "ES"] },
    { name: "A. Vidal", team: "Juventus", era: "14/15", ovr: 90, roles: ["CC", "TRQ", "MED"] },
    { name: "C. Marchisio", team: "Juventus", era: "14/15", ovr: 88, roles: ["CC", "MED"] },
    { name: "C. Tevez", team: "Juventus", era: "14/15", ovr: 92, roles: ["ATT", "TRQ"] },
    { name: "A. Morata", team: "Juventus", era: "14/15", ovr: 85, roles: ["ATT", "AS"] },
    { name: "F. Llorente", team: "Juventus", era: "14/15", ovr: 84, roles: ["ATT"] },
    { name: "R. Pereyra", team: "Juventus", era: "14/15", ovr: 80, roles: ["CC", "TRQ", "ED"] },
    { name: "S. Padoin", team: "Juventus", era: "14/15", ovr: 75, roles: ["TD", "TS", "CC", "ED", "ES"] },
    { name: "M. Caceres", team: "Juventus", era: "14/15", ovr: 79, roles: ["DC", "TD", "TS"] },
    { name: "S. Sturaro", team: "Juventus", era: "14/15", ovr: 74, roles: ["CC", "MED"] },
    { name: "M. Storari", team: "Juventus", era: "14/15", ovr: 76, roles: ["POR"] },

    // MILAN 1988/89 (Gli Immortali di Sacchi)
    { name: "M. van Basten", team: "Milan", era: "88/89", ovr: 97, roles: ["ATT"] },
    { name: "R. Gullit", team: "Milan", era: "88/89", ovr: 95, roles: ["TRQ", "ATT", "CC"] },
    { name: "F. Rijkaard", team: "Milan", era: "88/89", ovr: 94, roles: ["MED", "CC", "DC"] },
    { name: "F. Baresi", team: "Milan", era: "88/89", ovr: 96, roles: ["DC"] },
    { name: "P. Maldini", team: "Milan", era: "88/89", ovr: 95, roles: ["TS", "DC"] },
    { name: "A. Costacurta", team: "Milan", era: "88/89", ovr: 90, roles: ["DC", "TD"] },
    { name: "M. Tassotti", team: "Milan", era: "88/89", ovr: 89, roles: ["TD"] },
    { name: "G. Galli", team: "Milan", era: "88/89", ovr: 86, roles: ["POR"] },
    { name: "R. Donadoni", team: "Milan", era: "88/89", ovr: 91, roles: ["ED", "ES", "TRQ", "AD", "AS"] },
    { name: "C. Ancelotti", team: "Milan", era: "88/89", ovr: 88, roles: ["CC", "MED"] },
    { name: "A. Evani", team: "Milan", era: "88/89", ovr: 85, roles: ["ES", "CC", "TS"] },
    { name: "P. Virdis", team: "Milan", era: "88/89", ovr: 83, roles: ["ATT"] },
    { name: "D. Albertini", team: "Milan", era: "88/89", ovr: 82, roles: ["CC", "MED"] },
    { name: "F. Galli", team: "Milan", era: "88/89", ovr: 82, roles: ["DC"] },
    { name: "C. Colombo", team: "Milan", era: "88/89", ovr: 76, roles: ["CC", "ED"] },
    { name: "R. Mussi", team: "Milan", era: "88/89", ovr: 77, roles: ["TD", "DC"] },
    { name: "G. Pinato", team: "Milan", era: "88/89", ovr: 71, roles: ["POR"] },
    
    // INTER 2009/10 (Il Triplete)
    { name: "J. César", team: "Inter", era: "09/10", ovr: 93, roles: ["POR"] },
    { name: "Maicon", team: "Inter", era: "09/10", ovr: 94, roles: ["TD", "ED"] },
    { name: "Lúcio", team: "Inter", era: "09/10", ovr: 91, roles: ["DC"] },
    { name: "W. Samuel", team: "Inter", era: "09/10", ovr: 91, roles: ["DC"] },
    { name: "J. Zanetti", team: "Inter", era: "09/10", ovr: 92, roles: ["TS", "TD", "MED", "CC"] },
    { name: "E. Cambiasso", team: "Inter", era: "09/10", ovr: 91, roles: ["MED", "CC"] },
    { name: "W. Sneijder", team: "Inter", era: "09/10", ovr: 95, roles: ["TRQ"] },
    { name: "S. Eto'o", team: "Inter", era: "09/10", ovr: 93, roles: ["ATT", "AS", "AD", "ES", "ED"] },
    { name: "D. Milito", team: "Inter", era: "09/10", ovr: 94, roles: ["ATT"] },
    { name: "G. Pandev", team: "Inter", era: "09/10", ovr: 85, roles: ["AD", "AS", "TRQ", "ATT"] },
    { name: "T. Motta", team: "Inter", era: "09/10", ovr: 87, roles: ["CC", "MED"] },
    { name: "D. Stankovic", team: "Inter", era: "09/10", ovr: 88, roles: ["CC", "TRQ"] },
    { name: "C. Chivu", team: "Inter", era: "09/10", ovr: 85, roles: ["TS", "DC"] },
    { name: "I. Córdoba", team: "Inter", era: "09/10", ovr: 84, roles: ["DC", "TD"] },
    { name: "M. Materazzi", team: "Inter", era: "09/10", ovr: 82, roles: ["DC"] },
    { name: "M. Balotelli", team: "Inter", era: "09/10", ovr: 83, roles: ["ATT", "AD", "AS"] },
    { name: "S. Muntari", team: "Inter", era: "09/10", ovr: 78, roles: ["CC", "MED"] },
    { name: "M. Mariga", team: "Inter", era: "09/10", ovr: 75, roles: ["CC", "MED"] },
    { name: "D. Santon", team: "Inter", era: "09/10", ovr: 77, roles: ["TS", "TD"] },
    { name: "F. Toldo", team: "Inter", era: "09/10", ovr: 80, roles: ["POR"] },

    // ROMA 2000/01
    { name: "F. Totti", team: "Roma", era: "00/01", ovr: 96, roles: ["TRQ", "ATT", "AS"] },
    { name: "G. Batistuta", team: "Roma", era: "00/01", ovr: 94, roles: ["ATT"] },
    { name: "V. Montella", team: "Roma", era: "00/01", ovr: 89, roles: ["ATT"] },
    { name: "Cafu", team: "Roma", era: "00/01", ovr: 93, roles: ["TD", "ED"] },
    { name: "V. Candela", team: "Roma", era: "00/01", ovr: 88, roles: ["TS", "ES"] },
    { name: "W. Samuel", team: "Roma", era: "00/01", ovr: 90, roles: ["DC"] },
    { name: "Aldair", team: "Roma", era: "00/01", ovr: 89, roles: ["DC"] },
    { name: "Antônio Carlos Zago", team: "Roma", era: "00/01", ovr: 86, roles: ["DC"] },
    { name: "Emerson", team: "Roma", era: "00/01", ovr: 88, roles: ["MED", "CC"] },
    { name: "D. Tommasi", team: "Roma", era: "00/01", ovr: 86, roles: ["CC", "MED", "ED"] },
    { name: "C. Zanetti", team: "Roma", era: "00/01", ovr: 83, roles: ["MED", "CC"] },
    { name: "F. Antonioli", team: "Roma", era: "00/01", ovr: 83, roles: ["POR"] },
    { name: "H. Nakata", team: "Roma", era: "00/01", ovr: 85, roles: ["TRQ", "CC"] },
    { name: "M. Delvecchio", team: "Roma", era: "00/01", ovr: 84, roles: ["ATT"] },
    { name: "A. Mangone", team: "Roma", era: "00/01", ovr: 77, roles: ["DC"] },
    { name: "G. Guigou", team: "Roma", era: "00/01", ovr: 76, roles: ["ES", "CC", "TS"] },
    { name: "C. Lupatelli", team: "Roma", era: "00/01", ovr: 75, roles: ["POR"] },

    // LAZIO 1999/00
    { name: "A. Nesta", team: "Lazio", era: "99/00", ovr: 95, roles: ["DC"] },
    { name: "J.S. Verón", team: "Lazio", era: "99/00", ovr: 94, roles: ["CC", "TRQ"] },
    { name: "P. Nedved", team: "Lazio", era: "99/00", ovr: 92, roles: ["ES", "AS", "TRQ"] },
    { name: "M. Salas", team: "Lazio", era: "99/00", ovr: 91, roles: ["ATT"] },
    { name: "S. Mihajlovic", team: "Lazio", era: "99/00", ovr: 90, roles: ["DC", "TS"] },
    { name: "D. Simeone", team: "Lazio", era: "99/00", ovr: 89, roles: ["MED", "CC"] },
    { name: "R. Mancini", team: "Lazio", era: "99/00", ovr: 89, roles: ["TRQ", "ATT"] },
    { name: "L. Marchegiani", team: "Lazio", era: "99/00", ovr: 89, roles: ["POR"] },
    { name: "M. Almeyda", team: "Lazio", era: "99/00", ovr: 88, roles: ["MED", "CC"] },
    { name: "S. Conceição", team: "Lazio", era: "99/00", ovr: 87, roles: ["ED", "AD"] },
    { name: "F. Couto", team: "Lazio", era: "99/00", ovr: 85, roles: ["DC"] },
    { name: "P. Negro", team: "Lazio", era: "99/00", ovr: 84, roles: ["DC", "TD"] },
    { name: "G. Pancaro", team: "Lazio", era: "99/00", ovr: 83, roles: ["TS", "TD"] },
    { name: "F. Ravanelli", team: "Lazio", era: "99/00", ovr: 84, roles: ["ATT"] },
    { name: "S. Inzaghi", team: "Lazio", era: "99/00", ovr: 82, roles: ["ATT"] },
    { name: "A. Lombardo", team: "Lazio", era: "99/00", ovr: 80, roles: ["ED", "TD"] },
    { name: "N. Sensini", team: "Lazio", era: "99/00", ovr: 83, roles: ["DC", "MED"] },
    { name: "M. Ballotta", team: "Lazio", era: "99/00", ovr: 76, roles: ["POR"] },

    // NAPOLI 1986/87 (Primo Scudetto)
    { name: "D. Maradona", team: "Napoli", era: "86/87", ovr: 99, roles: ["TRQ", "ATT", "AD", "AS"] },
    { name: "C. Ferrara", team: "Napoli", era: "86/87", ovr: 89, roles: ["DC", "TD"] },
    { name: "S. Bagni", team: "Napoli", era: "86/87", ovr: 87, roles: ["MED", "CC"] },
    { name: "F. De Napoli", team: "Napoli", era: "86/87", ovr: 86, roles: ["CC", "ED"] },
    { name: "C. Garella", team: "Napoli", era: "86/87", ovr: 85, roles: ["POR"] },
    { name: "G. Bruscolotti", team: "Napoli", era: "86/87", ovr: 85, roles: ["TD", "DC"] },
    { name: "A. Carnevale", team: "Napoli", era: "86/87", ovr: 84, roles: ["ATT"] },
    { name: "A. Renica", team: "Napoli", era: "86/87", ovr: 84, roles: ["DC"] },
    { name: "B. Giordano", team: "Napoli", era: "86/87", ovr: 85, roles: ["ATT"] },
    { name: "G. Volpecina", team: "Napoli", era: "86/87", ovr: 80, roles: ["TS", "ES"] },
    { name: "M. Ferrario", team: "Napoli", era: "86/87", ovr: 82, roles: ["DC"] },
    { name: "F. Romano", team: "Napoli", era: "86/87", ovr: 79, roles: ["CC", "MED"] },
    { name: "L. Caffarelli", team: "Napoli", era: "86/87", ovr: 76, roles: ["TRQ", "CC", "ES"] },
    { name: "C. Sola", team: "Napoli", era: "86/87", ovr: 74, roles: ["CC"] },
    { name: "R. Di Fusco", team: "Napoli", era: "86/87", ovr: 71, roles: ["POR"] },

    // SAMPDORIA 1990/91 (Scudetto)
    { name: "G. Vialli", team: "Sampdoria", era: "90/91", ovr: 92, roles: ["ATT"] },
    { name: "R. Mancini", team: "Sampdoria", era: "90/91", ovr: 91, roles: ["TRQ", "ATT", "AS"] },
    { name: "P. Vierchowod", team: "Sampdoria", era: "90/91", ovr: 91, roles: ["DC"] },
    { name: "G. Pagliuca", team: "Sampdoria", era: "90/91", ovr: 89, roles: ["POR"] },
    { name: "T. Cerezo", team: "Sampdoria", era: "90/91", ovr: 88, roles: ["CC", "MED"] },
    { name: "A. Lombardo", team: "Sampdoria", era: "90/91", ovr: 87, roles: ["ED", "AD", "TD"] },
    { name: "S. Katanec", team: "Sampdoria", era: "90/91", ovr: 86, roles: ["MED", "CC", "DC"] },
    { name: "G. Dossena", team: "Sampdoria", era: "90/91", ovr: 85, roles: ["ES", "CC", "TS"] },
    { name: "F. Pari", team: "Sampdoria", era: "90/91", ovr: 84, roles: ["MED", "TD"] },
    { name: "M. Mannini", team: "Sampdoria", era: "90/91", ovr: 83, roles: ["TD", "DC"] },
    { name: "M. Lanna", team: "Sampdoria", era: "90/91", ovr: 81, roles: ["TS", "DC"] },
    { name: "M. Branca", team: "Sampdoria", era: "90/91", ovr: 80, roles: ["ATT"] },
    { name: "G. Invernizzi", team: "Sampdoria", era: "90/91", ovr: 78, roles: ["CC", "MED"] },
    { name: "U. Calcagno", team: "Sampdoria", era: "90/91", ovr: 72, roles: ["ES", "CC"] },
    { name: "G. Nuciari", team: "Sampdoria", era: "90/91", ovr: 71, roles: ["POR"] },

    // FIORENTINA 1998/99 (Trapattoni)
    { name: "G. Batistuta", team: "Fiorentina", era: "98/99", ovr: 95, roles: ["ATT"] },
    { name: "Rui Costa", team: "Fiorentina", era: "98/99", ovr: 93, roles: ["TRQ", "CC"] },
    { name: "F. Toldo", team: "Fiorentina", era: "98/99", ovr: 90, roles: ["POR"] },
    { name: "Edmundo", team: "Fiorentina", era: "98/99", ovr: 88, roles: ["ATT", "AS", "AD", "TRQ"] },
    { name: "L. Oliveira", team: "Fiorentina", era: "98/99", ovr: 85, roles: ["ATT", "AD", "AS"] },
    { name: "T. Repka", team: "Fiorentina", era: "98/99", ovr: 84, roles: ["DC", "TD"] },
    { name: "M. Torricelli", team: "Fiorentina", era: "98/99", ovr: 84, roles: ["TD", "DC", "TS"] },
    { name: "J. Heinrich", team: "Fiorentina", era: "98/99", ovr: 82, roles: ["TS", "ES", "DC"] },
    { name: "S. Cois", team: "Fiorentina", era: "98/99", ovr: 81, roles: ["MED", "CC"] },
    { name: "G. Falcone", team: "Fiorentina", era: "98/99", ovr: 80, roles: ["DC"] },
    { name: "A. Padalino", team: "Fiorentina", era: "98/99", ovr: 78, roles: ["DC", "TD"] },
    { name: "M. Amoroso", team: "Fiorentina", era: "98/99", ovr: 78, roles: ["CC", "MED"] },
    { name: "A. Robbiati", team: "Fiorentina", era: "98/99", ovr: 79, roles: ["TRQ", "AS", "ES", "ATT"] },
    { name: "D. Ficini", team: "Fiorentina", era: "98/99", ovr: 75, roles: ["CC", "MED"] },
    { name: "C. Amoruso", team: "Fiorentina", era: "98/99", ovr: 77, roles: ["ATT"] },
    { name: "G. Mareggini", team: "Fiorentina", era: "98/99", ovr: 72, roles: ["POR"] },

    // PARMA 1998/99 (UEFA)
    { name: "L. Thuram", team: "Parma", era: "98/99", ovr: 92, roles: ["DC", "TD"] },
    { name: "J.S. Verón", team: "Parma", era: "98/99", ovr: 91, roles: ["CC", "TRQ"] },
    { name: "H. Crespo", team: "Parma", era: "98/99", ovr: 91, roles: ["ATT"] },
    { name: "F. Cannavaro", team: "Parma", era: "98/99", ovr: 90, roles: ["DC"] },
    { name: "G. Buffon", team: "Parma", era: "98/99", ovr: 89, roles: ["POR"] },
    { name: "E. Chiesa", team: "Parma", era: "98/99", ovr: 88, roles: ["ATT", "AD", "AS"] },
    { name: "R. Sensini", team: "Parma", era: "98/99", ovr: 86, roles: ["DC", "MED"] },
    { name: "D. Baggio", team: "Parma", era: "98/99", ovr: 86, roles: ["CC", "MED"] },
    { name: "A. Benarrivo", team: "Parma", era: "98/99", ovr: 85, roles: ["TS", "TD"] },
    { name: "D. Fuser", team: "Parma", era: "98/99", ovr: 85, roles: ["ED", "TD", "CC"] },
    { name: "F. Asprilla", team: "Parma", era: "98/99", ovr: 84, roles: ["ATT", "AS", "AD", "TRQ"] },
    { name: "A. Boghossian", team: "Parma", era: "98/99", ovr: 84, roles: ["CC", "MED"] },
    { name: "P. Vanoli", team: "Parma", era: "98/99", ovr: 82, roles: ["TS", "ES"] },
    { name: "M. Stanic", team: "Parma", era: "98/99", ovr: 82, roles: ["ED", "TRQ", "ATT", "CC"] },
    { name: "A. Balbo", team: "Parma", era: "98/99", ovr: 83, roles: ["ATT"] },
    { name: "L. Apolloni", team: "Parma", era: "98/99", ovr: 79, roles: ["DC"] },
    { name: "R. Mussi", team: "Parma", era: "98/99", ovr: 77, roles: ["TD", "TS"] },
    { name: "A. Nista", team: "Parma", era: "98/99", ovr: 72, roles: ["POR"] },

    // --- LE PROVINCIALI & SQUADRE CULT ---

    // CHIEVO 2001/02
    { name: "E. Corini", team: "Chievo", era: "01/02", ovr: 83, roles: ["CC", "MED"] },
    { name: "S. Perrotta", team: "Chievo", era: "01/02", ovr: 81, roles: ["CC", "MED"] },
    { name: "M. Marazzina", team: "Chievo", era: "01/02", ovr: 80, roles: ["ATT"] },
    { name: "B. Corradi", team: "Chievo", era: "01/02", ovr: 79, roles: ["ATT"] },
    { name: "Eriberto", team: "Chievo", era: "01/02", ovr: 79, roles: ["ED", "AD"] },
    { name: "C. Manfredini", team: "Chievo", era: "01/02", ovr: 78, roles: ["ES", "AS"] },
    { name: "N. Legrottaglie", team: "Chievo", era: "01/02", ovr: 78, roles: ["DC"] },
    { name: "C. Lupatelli", team: "Chievo", era: "01/02", ovr: 77, roles: ["POR"] },
    { name: "L. D'Anna", team: "Chievo", era: "01/02", ovr: 76, roles: ["DC"] },
    { name: "S. Lanna", team: "Chievo", era: "01/02", ovr: 76, roles: ["TS", "DC"] },
    { name: "F. Cossato", team: "Chievo", era: "01/02", ovr: 76, roles: ["ATT"] },
    { name: "F. Moro", team: "Chievo", era: "01/02", ovr: 75, roles: ["TD"] },
    { name: "M. D'Angelo", team: "Chievo", era: "01/02", ovr: 75, roles: ["DC"] },
    { name: "A. Zanchetta", team: "Chievo", era: "01/02", ovr: 74, roles: ["CC", "MED"] },
    { name: "J. Mensah", team: "Chievo", era: "01/02", ovr: 73, roles: ["DC", "TS"] },
    { name: "S. Barone", team: "Chievo", era: "01/02", ovr: 72, roles: ["CC"] },
    { name: "G. Frezzolini", team: "Chievo", era: "01/02", ovr: 71, roles: ["POR"] },

    // BRESCIA 2000/01
    { name: "R. Baggio", team: "Brescia", era: "00/01", ovr: 92, roles: ["TRQ", "ATT", "AS"] },
    { name: "D. Hubner", team: "Brescia", era: "00/01", ovr: 84, roles: ["ATT"] },
    { name: "A. Pirlo", team: "Brescia", era: "00/01", ovr: 82, roles: ["MED", "CC", "TRQ"] },
    { name: "Matuzalém", team: "Brescia", era: "00/01", ovr: 79, roles: ["CC", "MED"] },
    { name: "D. Bonera", team: "Brescia", era: "00/01", ovr: 78, roles: ["DC", "TD"] },
    { name: "A. Diana", team: "Brescia", era: "00/01", ovr: 78, roles: ["TD", "ED"] },
    { name: "P. Srnicek", team: "Brescia", era: "00/01", ovr: 76, roles: ["POR"] },
    { name: "A. Calori", team: "Brescia", era: "00/01", ovr: 76, roles: ["DC"] },
    { name: "G. Martinez", team: "Brescia", era: "00/01", ovr: 76, roles: ["TS", "DC"] },
    { name: "I. Tare", team: "Brescia", era: "00/01", ovr: 76, roles: ["ATT"] },
    { name: "A. Filippini", team: "Brescia", era: "00/01", ovr: 75, roles: ["CC", "MED"] },
    { name: "E. Filippini", team: "Brescia", era: "00/01", ovr: 75, roles: ["CC", "ED"] },
    { name: "F. Petruzzi", team: "Brescia", era: "00/01", ovr: 75, roles: ["DC"] },
    { name: "L. Castellazzi", team: "Brescia", era: "00/01", ovr: 74, roles: ["POR"] },
    { name: "A. Sussi", team: "Brescia", era: "00/01", ovr: 73, roles: ["TS", "ES"] },
    { name: "A. Yllana", team: "Brescia", era: "00/01", ovr: 72, roles: ["CC"] },

    // PALERMO 2009/10
    { name: "F. Miccoli", team: "Palermo", era: "09/10", ovr: 87, roles: ["ATT", "TRQ", "AS"] },
    { name: "E. Cavani", team: "Palermo", era: "09/10", ovr: 85, roles: ["ATT", "AD", "AS"] },
    { name: "J. Pastore", team: "Palermo", era: "09/10", ovr: 85, roles: ["TRQ", "AS", "CC"] },
    { name: "S. Kjaer", team: "Palermo", era: "09/10", ovr: 83, roles: ["DC"] },
    { name: "S. Sirigu", team: "Palermo", era: "09/10", ovr: 82, roles: ["POR"] },
    { name: "F. Balzaretti", team: "Palermo", era: "09/10", ovr: 82, roles: ["TS", "ES"] },
    { name: "A. Nocerino", team: "Palermo", era: "09/10", ovr: 81, roles: ["CC", "MED"] },
    { name: "F. Liverani", team: "Palermo", era: "09/10", ovr: 81, roles: ["CC", "MED"] },
    { name: "Fábio Simplício", team: "Palermo", era: "09/10", ovr: 80, roles: ["CC", "TRQ"] },
    { name: "M. Cassani", team: "Palermo", era: "09/10", ovr: 80, roles: ["TD", "ED"] },
    { name: "G. Migliaccio", team: "Palermo", era: "09/10", ovr: 79, roles: ["MED", "CC"] },
    { name: "M. Bresciano", team: "Palermo", era: "09/10", ovr: 79, roles: ["ED", "ES", "CC"] },
    { name: "C. Bovo", team: "Palermo", era: "09/10", ovr: 78, roles: ["DC"] },
    { name: "A. Hernandez", team: "Palermo", era: "09/10", ovr: 77, roles: ["ATT"] },
    { name: "D. Goian", team: "Palermo", era: "09/10", ovr: 75, roles: ["DC"] },
    { name: "Rubinho", team: "Palermo", era: "09/10", ovr: 73, roles: ["POR"] },

    // UDINESE 2010/11
    { name: "A. Di Natale", team: "Udinese", era: "10/11", ovr: 90, roles: ["ATT", "AS"] },
    { name: "A. Sánchez", team: "Udinese", era: "10/11", ovr: 88, roles: ["AD", "TRQ", "ATT", "AS"] },
    { name: "S. Handanovic", team: "Udinese", era: "10/11", ovr: 86, roles: ["POR"] },
    { name: "G. Inler", team: "Udinese", era: "10/11", ovr: 84, roles: ["CC", "MED"] },
    { name: "M. Benatia", team: "Udinese", era: "10/11", ovr: 84, roles: ["DC"] },
    { name: "M. Isla", team: "Udinese", era: "10/11", ovr: 83, roles: ["TD", "ED", "CC"] },
    { name: "K. Asamoah", team: "Udinese", era: "10/11", ovr: 83, roles: ["CC", "ES", "MED"] },
    { name: "C. Zapata", team: "Udinese", era: "10/11", ovr: 82, roles: ["DC", "TD"] },
    { name: "P. Armero", team: "Udinese", era: "10/11", ovr: 82, roles: ["TS", "ES"] },
    { name: "M. Domizzi", team: "Udinese", era: "10/11", ovr: 79, roles: ["DC", "TS"] },
    { name: "G. Denis", team: "Udinese", era: "10/11", ovr: 79, roles: ["ATT"] },
    { name: "G. Pinzi", team: "Udinese", era: "10/11", ovr: 78, roles: ["CC", "MED"] },
    { name: "E. Badu", team: "Udinese", era: "10/11", ovr: 76, roles: ["CC"] },
    { name: "G. Pasquale", team: "Udinese", era: "10/11", ovr: 76, roles: ["TS", "ES"] },
    { name: "A. Coda", team: "Udinese", era: "10/11", ovr: 75, roles: ["DC"] },
    { name: "E. Belardi", team: "Udinese", era: "10/11", ovr: 72, roles: ["POR"] },

    // EMPOLI 2005/06 (La Banda Somma)
    { name: "F. Tavano", team: "Empoli", era: "05/06", ovr: 83, roles: ["ATT", "AS", "AD"] },
    { name: "S. Almiron", team: "Empoli", era: "05/06", ovr: 81, roles: ["CC", "MED"] },
    { name: "I. Vannucchi", team: "Empoli", era: "05/06", ovr: 80, roles: ["TRQ", "ES"] },
    { name: "R. Pratali", team: "Empoli", era: "05/06", ovr: 78, roles: ["DC"] },
    { name: "M. Riganò", team: "Empoli", era: "05/06", ovr: 78, roles: ["ATT"] },
    { name: "D. Moro", team: "Empoli", era: "05/06", ovr: 77, roles: ["CC", "MED"] },
    { name: "A. Buscè", team: "Empoli", era: "05/06", ovr: 77, roles: ["TD", "ED"] },
    { name: "G. Balli", team: "Empoli", era: "05/06", ovr: 76, roles: ["POR"] },
    { name: "A. Lucchini", team: "Empoli", era: "05/06", ovr: 76, roles: ["DC"] },
    { name: "R. Bonetto", team: "Empoli", era: "05/06", ovr: 75, roles: ["TS"] },
    { name: "A. Ficini", team: "Empoli", era: "05/06", ovr: 74, roles: ["CC", "MED"] },
    { name: "V. Coda", team: "Empoli", era: "05/06", ovr: 74, roles: ["DC"] },
    { name: "F. Lodi", team: "Empoli", era: "05/06", ovr: 73, roles: ["CC", "TRQ"] },
    { name: "S. Pozzi", team: "Empoli", era: "05/06", ovr: 73, roles: ["ATT"] },
    { name: "C. Dossena", team: "Empoli", era: "05/06", ovr: 70, roles: ["POR"] },

    // LECCE 2004/05 (Zemanlandia)
    { name: "V. Bojinov", team: "Lecce", era: "04/05", ovr: 82, roles: ["ATT", "AD"] },
    { name: "M. Vucinic", team: "Lecce", era: "04/05", ovr: 81, roles: ["ATT", "AS"] },
    { name: "M. Cassetti", team: "Lecce", era: "04/05", ovr: 80, roles: ["TD", "ED", "CC"] },
    { name: "C. Ledesma", team: "Lecce", era: "04/05", ovr: 79, roles: ["CC", "MED"] },
    { name: "G. Giacomazzi", team: "Lecce", era: "04/05", ovr: 79, roles: ["MED", "CC"] },
    { name: "A. Dalla Bona", team: "Lecce", era: "04/05", ovr: 78, roles: ["CC"] },
    { name: "L. Stovini", team: "Lecce", era: "04/05", ovr: 77, roles: ["DC"] },
    { name: "S. Sicignano", team: "Lecce", era: "04/05", ovr: 76, roles: ["POR"] },
    { name: "A. Pinardi", team: "Lecce", era: "04/05", ovr: 76, roles: ["CC", "TRQ"] },
    { name: "G. Diamoutene", team: "Lecce", era: "04/05", ovr: 75, roles: ["DC"] },
    { name: "A. Bjelanovic", team: "Lecce", era: "04/05", ovr: 75, roles: ["ATT"] },
    { name: "P. Rullo", team: "Lecce", era: "04/05", ovr: 74, roles: ["TS"] },
    { name: "C. Bovo", team: "Lecce", era: "04/05", ovr: 74, roles: ["DC"] },
    { name: "B. Konan", team: "Lecce", era: "04/05", ovr: 73, roles: ["ATT"] },
    { name: "V. Rosati", team: "Lecce", era: "04/05", ovr: 71, roles: ["POR"] },

    // CATANIA 2006/07
    { name: "J. Vargas", team: "Catania", era: "06/07", ovr: 82, roles: ["TS", "ES"] },
    { name: "G. Mascara", team: "Catania", era: "06/07", ovr: 81, roles: ["TRQ", "AS", "ATT"] },
    { name: "G. Spinesi", team: "Catania", era: "06/07", ovr: 80, roles: ["ATT"] },
    { name: "A. Pantanelli", team: "Catania", era: "06/07", ovr: 78, roles: ["POR"] },
    { name: "L. Stovini", team: "Catania", era: "06/07", ovr: 78, roles: ["DC"] },
    { name: "M. Edusei", team: "Catania", era: "06/07", ovr: 77, roles: ["MED", "CC"] },
    { name: "M. Baiocco", team: "Catania", era: "06/07", ovr: 77, roles: ["CC", "MED"] },
    { name: "F. Caserta", team: "Catania", era: "06/07", ovr: 76, roles: ["CC", "TRQ"] },
    { name: "G. Colucci", team: "Catania", era: "06/07", ovr: 76, roles: ["ATT"] },
    { name: "C. Silvestri", team: "Catania", era: "06/07", ovr: 75, roles: ["DC"] },
    { name: "M. Izco", team: "Catania", era: "06/07", ovr: 75, roles: ["CC"] },
    { name: "G. Sardo", team: "Catania", era: "06/07", ovr: 74, roles: ["TD"] },
    { name: "M. Corona", team: "Catania", era: "06/07", ovr: 74, roles: ["ATT"] },
    { name: "R. Minelli", team: "Catania", era: "06/07", ovr: 73, roles: ["DC"] },
    { name: "C. Bizzarri", team: "Catania", era: "06/07", ovr: 72, roles: ["POR"] },

    // SIENA 2007/08
    { name: "M. Maccarone", team: "Siena", era: "07/08", ovr: 82, roles: ["ATT"] },
    { name: "S. Vergassola", team: "Siena", era: "07/08", ovr: 80, roles: ["MED", "CC"] },
    { name: "A. Manninger", team: "Siena", era: "07/08", ovr: 79, roles: ["POR"] },
    { name: "H. Kharja", team: "Siena", era: "07/08", ovr: 79, roles: ["CC", "TRQ"] },
    { name: "S. Loria", team: "Siena", era: "07/08", ovr: 78, roles: ["DC"] },
    { name: "D. Portanova", team: "Siena", era: "07/08", ovr: 78, roles: ["DC"] },
    { name: "C. Zuniga", team: "Siena", era: "07/08", ovr: 77, roles: ["TD", "ED", "TS"] },
    { name: "M. Locatelli", team: "Siena", era: "07/08", ovr: 76, roles: ["TRQ", "AS", "ES"] },
    { name: "P. Galloppa", team: "Siena", era: "07/08", ovr: 76, roles: ["CC", "MED"] },
    { name: "A. Rosina", team: "Siena", era: "07/08", ovr: 77, roles: ["TRQ", "AD", "AS"] },
    { name: "C. Riganò", team: "Siena", era: "07/08", ovr: 76, roles: ["ATT"] },
    { name: "P. De Ceglie", team: "Siena", era: "07/08", ovr: 75, roles: ["TS", "ES"] },
    { name: "L. Bertotto", team: "Siena", era: "07/08", ovr: 75, roles: ["DC"] },
    { name: "A. Coppola", team: "Siena", era: "07/08", ovr: 74, roles: ["CC"] },
    { name: "D. Eleftheropoulos", team: "Siena", era: "07/08", ovr: 72, roles: ["POR"] },
// database.js - Blocco 2 (Estensione database)
// Aggiungi queste squadre in coda al file esistente, prima della ] finale.

    // BOLOGNA 1997/98 (Baggio & Signori)
    { name: "R. Baggio", team: "Bologna", era: "97/98", ovr: 92, roles: ["TRQ", "ATT", "AS"] },
    { name: "G. Signori", team: "Bologna", era: "97/98", ovr: 89, roles: ["ATT", "AS", "AD"] },
    { name: "F. Antonioli", team: "Bologna", era: "97/98", ovr: 83, roles: ["POR"] },
    { name: "M. Paramatti", team: "Bologna", era: "97/98", ovr: 78, roles: ["TS", "TD"] },
    { name: "G. Mangone", team: "Bologna", era: "97/98", ovr: 77, roles: ["DC"] },
    { name: "M. Paganin", team: "Bologna", era: "97/98", ovr: 77, roles: ["DC"] },
    { name: "K. Andersson", team: "Bologna", era: "97/98", ovr: 80, roles: ["ATT"] },
    { name: "I. Shalimov", team: "Bologna", era: "97/98", ovr: 79, roles: ["CC", "TRQ"] },
    { name: "M. Binotto", team: "Bologna", era: "97/98", ovr: 75, roles: ["ED", "AD"] },
    { name: "G. Maini", team: "Bologna", era: "97/98", ovr: 76, roles: ["CC", "ED"] },
    { name: "N. Nervo", team: "Bologna", era: "97/98", ovr: 75, roles: ["ED", "CC"] },
    { name: "M. Boselli", team: "Bologna", era: "97/98", ovr: 73, roles: ["DC"] },
    { name: "T. Turkyilmaz", team: "Bologna", era: "97/98", ovr: 74, roles: ["ATT"] },

    // PERUGIA 2000/01 (Cosmi)
    { name: "M. Materazzi", team: "Perugia", era: "00/01", ovr: 84, roles: ["DC"] },
    { name: "D. Liverani", team: "Perugia", era: "00/01", ovr: 82, roles: ["CC", "MED"] },
    { name: "Z. Vryzas", team: "Perugia", era: "00/01", ovr: 78, roles: ["ATT"] },
    { name: "A. Mazzantini", team: "Perugia", era: "00/01", ovr: 76, roles: ["POR"] },
    { name: "S. Blasi", team: "Perugia", era: "00/01", ovr: 76, roles: ["MED", "TD"] },
    { name: "D. Baiocco", team: "Perugia", era: "00/01", ovr: 75, roles: ["CC", "ED"] },
    { name: "F. Ze Maria", team: "Perugia", era: "00/01", ovr: 77, roles: ["TD", "ED"] },
    { name: "G. Tedesco", team: "Perugia", era: "00/01", ovr: 74, roles: ["CC"] },
    { name: "M. Di Loreto", team: "Perugia", era: "00/01", ovr: 74, roles: ["DC"] },

    // ATALANTA 2007/08 (Zampagna/Doni)
    { name: "C. Doni", team: "Atalanta", era: "07/08", ovr: 84, roles: ["TRQ", "ATT", "AS"] },
    { name: "R. Zampagna", team: "Atalanta", era: "07/08", ovr: 80, roles: ["ATT"] },
    { name: "F. Coppola", team: "Atalanta", era: "07/08", ovr: 78, roles: ["POR"] },
    { name: "L. Cigarini", team: "Atalanta", era: "07/08", ovr: 79, roles: ["CC", "MED"] },
    { name: "M. Cassetti", team: "Atalanta", era: "07/08", ovr: 77, roles: ["TD"] },
    { name: "T. Manfredini", team: "Atalanta", era: "07/08", ovr: 76, roles: ["DC"] },
    { name: "R. Montolivo", team: "Atalanta", era: "07/08", ovr: 80, roles: ["CC", "TRQ"] },
    { name: "S. Padoin", team: "Atalanta", era: "07/08", ovr: 75, roles: ["CC", "TD", "ED"] },

    // BOLOGNA 2011/12 (Diamanti/Di Vaio)
    { name: "A. Diamanti", team: "Bologna", era: "11/12", ovr: 83, roles: ["TRQ", "AD", "AS"] },
    { name: "M. Di Vaio", team: "Bologna", era: "11/12", ovr: 82, roles: ["ATT"] },
    { name: "F. Gillet", team: "Bologna", era: "11/12", ovr: 80, roles: ["POR"] },
    { name: "G. Mudingayi", team: "Bologna", era: "11/12", ovr: 79, roles: ["MED", "CC"] },
    { name: "D. Portanova", team: "Bologna", era: "11/12", ovr: 78, roles: ["DC"] },
    { name: "G. Ramirez", team: "Bologna", era: "11/12", ovr: 81, roles: ["TRQ", "CC"] },
    { name: "S. Loria", team: "Bologna", era: "11/12", ovr: 75, roles: ["DC"] },
    { name: "A. Raggi", team: "Bologna", era: "11/12", ovr: 74, roles: ["TD", "DC"] },

    // GENOA 2008/09 (Gasperini - Milito/Thiago Motta)
    { name: "D. Milito", team: "Genoa", era: "08/09", ovr: 88, roles: ["ATT"] },
    { name: "T. Motta", team: "Genoa", era: "08/09", ovr: 86, roles: ["CC", "MED"] },
    { name: "S. Frey", team: "Genoa", era: "08/09", ovr: 85, roles: ["POR"] },
    { name: "D. Criscito", team: "Genoa", era: "08/09", ovr: 82, roles: ["TS", "DC"] },
    { name: "G. Sculli", team: "Genoa", era: "08/09", ovr: 80, roles: ["AS", "AD", "ATT"] },
    { name: "M. Rossi", team: "Genoa", era: "08/09", ovr: 80, roles: ["ED", "TD"] },
    { name: "S. Bocchetti", team: "Genoa", era: "08/09", ovr: 79, roles: ["DC", "TS"] },
    { name: "G. Biava", team: "Genoa", era: "08/09", ovr: 77, roles: ["DC"] },
    { name: "O. Kharja", team: "Genoa", era: "08/09", ovr: 78, roles: ["CC", "TRQ"] },
    { name: "A. Mesto", team: "Genoa", era: "08/09", ovr: 77, roles: ["ED", "TD"] },

    // TORINO 2013/14 (Cerci/Immobile)
    { name: "C. Immobile", team: "Torino", era: "13/14", ovr: 87, roles: ["ATT"] },
    { name: "A. Cerci", team: "Torino", era: "13/14", ovr: 85, roles: ["AD", "ATT", "ED"] },
    { name: "D. Padelli", team: "Torino", era: "13/14", ovr: 78, roles: ["POR"] },
    { name: "K. Glik", team: "Torino", era: "13/14", ovr: 82, roles: ["DC"] },
    { name: "M. Darmian", team: "Torino", era: "13/14", ovr: 81, roles: ["TD", "TS"] },
    { name: "G. Vives", team: "Torino", era: "13/14", ovr: 77, roles: ["CC", "MED"] },
    { name: "O. El Kaddouri", team: "Torino", era: "13/14", ovr: 78, roles: ["TRQ", "ED", "ES"] },
    { name: "E. Moretti", team: "Torino", era: "13/14", ovr: 77, roles: ["DC", "TS"] },
    { name: "N. Maksimovic", team: "Torino", era: "13/14", ovr: 78, roles: ["DC"] },

    // CAGLIARI 2012/13 (Nainggolan/Astori)
    { name: "R. Nainggolan", team: "Cagliari", era: "12/13", ovr: 84, roles: ["CC", "MED"] },
    { name: "D. Astori", team: "Cagliari", era: "12/13", ovr: 81, roles: ["DC"] },
    { name: "M. Agazzi", team: "Cagliari", era: "12/13", ovr: 77, roles: ["POR"] },
    { name: "M. Sau", team: "Cagliari", era: "12/13", ovr: 79, roles: ["ATT", "AS"] },
    { name: "V. Ibarbo", team: "Cagliari", era: "12/13", ovr: 78, roles: ["AD", "ATT"] },
    { name: "A. Cossu", team: "Cagliari", era: "12/13", ovr: 79, roles: ["TRQ", "ED"] },
    { name: "D. Conti", team: "Cagliari", era: "12/13", ovr: 77, roles: ["CC", "MED"] },
    { name: "L. Rossettini", team: "Cagliari", era: "12/13", ovr: 76, roles: ["DC"] },
    { name: "F. Pisano", team: "Cagliari", era: "12/13", ovr: 74, roles: ["TD"] },
    // --- BLOCCO 3: CORAZZATE STORICHE E PROVINCIALI ---

    // MILAN 2006/07 (Champions League Ancelotti)
    { name: "Kakà", team: "Milan", era: "06/07", ovr: 94, roles: ["TRQ"] },
    { name: "C. Seedorf", team: "Milan", era: "06/07", ovr: 89, roles: ["TRQ", "CC", "ES"] },
    { name: "A. Pirlo", team: "Milan", era: "06/07", ovr: 90, roles: ["MED", "CC"] },
    { name: "G. Gattuso", team: "Milan", era: "06/07", ovr: 88, roles: ["MED", "CC"] },
    { name: "P. Maldini", team: "Milan", era: "06/07", ovr: 91, roles: ["DC", "TS"] },
    { name: "A. Nesta", team: "Milan", era: "06/07", ovr: 92, roles: ["DC"] },
    { name: "F. Inzaghi", team: "Milan", era: "06/07", ovr: 88, roles: ["ATT"] },
    { name: "Dida", team: "Milan", era: "06/07", ovr: 87, roles: ["POR"] },
    { name: "M. Oddo", team: "Milan", era: "06/07", ovr: 82, roles: ["TD"] },
    { name: "M. Jankulovski", team: "Milan", era: "06/07", ovr: 84, roles: ["TS"] },
    { name: "M. Ambrosini", team: "Milan", era: "06/07", ovr: 85, roles: ["CC", "MED"] },
    { name: "A. Gilardino", team: "Milan", era: "06/07", ovr: 83, roles: ["ATT"] },
    { name: "K. Kaladze", team: "Milan", era: "06/07", ovr: 83, roles: ["DC", "TS"] },
    { name: "C. Brocchi", team: "Milan", era: "06/07", ovr: 78, roles: ["CC", "MED"] },
    { name: "D. Bonera", team: "Milan", era: "06/07", ovr: 79, roles: ["DC", "TD"] },
    { name: "Z. Kalac", team: "Milan", era: "06/07", ovr: 74, roles: ["POR"] },

    // INTER 1997/98 (Ronaldo il Fenomeno)
    { name: "Ronaldo", team: "Inter", era: "97/98", ovr: 98, roles: ["ATT"] },
    { name: "Y. Djorkaeff", team: "Inter", era: "97/98", ovr: 87, roles: ["TRQ", "CC", "AS"] },
    { name: "I. Zamorano", team: "Inter", era: "97/98", ovr: 86, roles: ["ATT"] },
    { name: "D. Simeone", team: "Inter", era: "97/98", ovr: 86, roles: ["MED", "CC"] },
    { name: "J. Zanetti", team: "Inter", era: "97/98", ovr: 88, roles: ["TD", "TS", "MED"] },
    { name: "G. Pagliuca", team: "Inter", era: "97/98", ovr: 89, roles: ["POR"] },
    { name: "G. Bergomi", team: "Inter", era: "97/98", ovr: 85, roles: ["DC"] },
    { name: "T. West", team: "Inter", era: "97/98", ovr: 84, roles: ["DC", "TS"] },
    { name: "A. Winter", team: "Inter", era: "97/98", ovr: 82, roles: ["CC"] },
    { name: "F. Moriero", team: "Inter", era: "97/98", ovr: 81, roles: ["ED", "AD"] },
    { name: "B. Cauet", team: "Inter", era: "97/98", ovr: 80, roles: ["CC", "ES"] },
    { name: "L. Sartor", team: "Inter", era: "97/98", ovr: 78, roles: ["TD", "DC"] },
    { name: "S. Fresi", team: "Inter", era: "97/98", ovr: 76, roles: ["DC", "MED"] },
    { name: "F. Galante", team: "Inter", era: "97/98", ovr: 77, roles: ["DC"] },
    { name: "A. Mazzantini", team: "Inter", era: "97/98", ovr: 74, roles: ["POR"] },

    // JUVENTUS 1995/96 (La prima Champions di Lippi)
    { name: "A. Del Piero", team: "Juventus", era: "95/96", ovr: 92, roles: ["AS", "ATT", "TRQ"] },
    { name: "G. Vialli", team: "Juventus", era: "95/96", ovr: 90, roles: ["ATT"] },
    { name: "F. Ravanelli", team: "Juventus", era: "95/96", ovr: 88, roles: ["ATT", "AS"] },
    { name: "D. Deschamps", team: "Juventus", era: "95/96", ovr: 88, roles: ["MED", "CC"] },
    { name: "Paulo Sousa", team: "Juventus", era: "95/96", ovr: 87, roles: ["CC"] },
    { name: "A. Conte", team: "Juventus", era: "95/96", ovr: 85, roles: ["CC", "MED", "ED"] },
    { name: "A. Peruzzi", team: "Juventus", era: "95/96", ovr: 88, roles: ["POR"] },
    { name: "C. Ferrara", team: "Juventus", era: "95/96", ovr: 89, roles: ["DC", "TD"] },
    { name: "P. Vierchowod", team: "Juventus", era: "95/96", ovr: 86, roles: ["DC"] },
    { name: "G. Pessotto", team: "Juventus", era: "95/96", ovr: 83, roles: ["TS", "CC"] },
    { name: "M. Torricelli", team: "Juventus", era: "95/96", ovr: 84, roles: ["TD", "TS"] },
    { name: "A. Di Livio", team: "Juventus", era: "95/96", ovr: 84, roles: ["ED", "TD"] },
    { name: "M. Padovano", team: "Juventus", era: "95/96", ovr: 80, roles: ["ATT"] },
    { name: "A. Tacchinardi", team: "Juventus", era: "95/96", ovr: 79, roles: ["CC", "MED"] },
    { name: "S. Porrini", team: "Juventus", era: "95/96", ovr: 77, roles: ["TD", "DC"] },
    { name: "M. Rampulla", team: "Juventus", era: "95/96", ovr: 75, roles: ["POR"] },

    // ATALANTA 2019/20 (Il picco di Gasperini)
    { name: "P. Gomez", team: "Atalanta", era: "19/20", ovr: 88, roles: ["TRQ", "AS"] },
    { name: "J. Ilicic", team: "Atalanta", era: "19/20", ovr: 88, roles: ["TRQ", "AD", "ATT"] },
    { name: "D. Zapata", team: "Atalanta", era: "19/20", ovr: 86, roles: ["ATT"] },
    { name: "R. Gosens", team: "Atalanta", era: "19/20", ovr: 84, roles: ["TS", "ES"] },
    { name: "H. Hateboer", team: "Atalanta", era: "19/20", ovr: 83, roles: ["TD", "ED"] },
    { name: "M. De Roon", team: "Atalanta", era: "19/20", ovr: 82, roles: ["MED", "CC"] },
    { name: "R. Freuler", team: "Atalanta", era: "19/20", ovr: 82, roles: ["CC", "MED"] },
    { name: "M. Pasalic", team: "Atalanta", era: "19/20", ovr: 81, roles: ["CC", "TRQ"] },
    { name: "R. Toloi", team: "Atalanta", era: "19/20", ovr: 81, roles: ["DC", "TD"] },
    { name: "B. Djimsiti", team: "Atalanta", era: "19/20", ovr: 80, roles: ["DC"] },
    { name: "J. Palomino", team: "Atalanta", era: "19/20", ovr: 79, roles: ["DC"] },
    { name: "P. Gollini", team: "Atalanta", era: "19/20", ovr: 81, roles: ["POR"] },
    { name: "R. Malinovskyi", team: "Atalanta", era: "19/20", ovr: 82, roles: ["TRQ", "CC"] },
    { name: "L. Muriel", team: "Atalanta", era: "19/20", ovr: 83, roles: ["ATT", "AS"] },
    { name: "M. Sportiello", team: "Atalanta", era: "19/20", ovr: 78, roles: ["POR"] },

    // LAZIO 2019/20 (Inzaghi)
    { name: "C. Immobile", team: "Lazio", era: "19/20", ovr: 89, roles: ["ATT"] },
    { name: "S. Milinkovic-Savic", team: "Lazio", era: "19/20", ovr: 88, roles: ["CC", "TRQ"] },
    { name: "Luis Alberto", team: "Lazio", era: "19/20", ovr: 87, roles: ["TRQ", "CC"] },
    { name: "F. Acerbi", team: "Lazio", era: "19/20", ovr: 85, roles: ["DC"] },
    { name: "Lucas Leiva", team: "Lazio", era: "19/20", ovr: 83, roles: ["MED", "CC"] },
    { name: "M. Lazzari", team: "Lazio", era: "19/20", ovr: 82, roles: ["ED", "TD"] },
    { name: "S. Radu", team: "Lazio", era: "19/20", ovr: 82, roles: ["DC", "TS"] },
    { name: "T. Strakosha", team: "Lazio", era: "19/20", ovr: 80, roles: ["POR"] },
    { name: "J. Correa", team: "Lazio", era: "19/20", ovr: 83, roles: ["TRQ", "ATT", "AS"] },
    { name: "S. Lulic", team: "Lazio", era: "19/20", ovr: 81, roles: ["ES", "TS", "CC"] },
    { name: "Luiz Felipe", team: "Lazio", era: "19/20", ovr: 79, roles: ["DC"] },
    { name: "F. Caicedo", team: "Lazio", era: "19/20", ovr: 82, roles: ["ATT"] },
    { name: "A. Marusic", team: "Lazio", era: "19/20", ovr: 78, roles: ["ED", "ES"] },
    { name: "Patric", team: "Lazio", era: "19/20", ovr: 77, roles: ["DC", "TD"] },
    { name: "S. Proto", team: "Lazio", era: "19/20", ovr: 74, roles: ["POR"] },

    // SAMPDORIA 2009/10 (Pazzini & Cassano)
    { name: "A. Cassano", team: "Sampdoria", era: "09/10", ovr: 88, roles: ["TRQ", "AS", "ATT"] },
    { name: "G. Pazzini", team: "Sampdoria", era: "09/10", ovr: 86, roles: ["ATT"] },
    { name: "A. Palombo", team: "Sampdoria", era: "09/10", ovr: 84, roles: ["MED", "CC"] },
    { name: "D. Gastaldello", team: "Sampdoria", era: "09/10", ovr: 81, roles: ["DC"] },
    { name: "R. Ziegler", team: "Sampdoria", era: "09/10", ovr: 80, roles: ["TS", "ES"] },
    { name: "F. Semioli", team: "Sampdoria", era: "09/10", ovr: 79, roles: ["ED", "AD"] },
    { name: "S. Lucchini", team: "Sampdoria", era: "09/10", ovr: 78, roles: ["DC"] },
    { name: "L. Zauri", team: "Sampdoria", era: "09/10", ovr: 78, roles: ["TD", "TS"] },
    { name: "D. Mannini", team: "Sampdoria", era: "09/10", ovr: 78, roles: ["ES", "ED"] },
    { name: "A. Poli", team: "Sampdoria", era: "09/10", ovr: 77, roles: ["CC"] },
    { name: "F. Tissone", team: "Sampdoria", era: "09/10", ovr: 76, roles: ["CC", "MED"] },
    { name: "M. Rossi", team: "Sampdoria", era: "09/10", ovr: 75, roles: ["DC", "TD"] },
    { name: "L. Castellazzi", team: "Sampdoria", era: "09/10", ovr: 80, roles: ["POR"] },
    { name: "M. Storari", team: "Sampdoria", era: "09/10", ovr: 81, roles: ["POR"] },
    { name: "S. Guberti", team: "Sampdoria", era: "09/10", ovr: 78, roles: ["ED", "ES"] },

    // HELLAS VERONA 2013/14 (Toni & Iturbe)
    { name: "L. Toni", team: "Verona", era: "13/14", ovr: 84, roles: ["ATT"] },
    { name: "J. Iturbe", team: "Verona", era: "13/14", ovr: 83, roles: ["AD", "AS", "TRQ"] },
    { name: "Romulo", team: "Verona", era: "13/14", ovr: 79, roles: ["TD", "ED", "CC"] },
    { name: "Jorginho", team: "Verona", era: "13/14", ovr: 78, roles: ["CC", "MED"] },
    { name: "J. Gomez Taleb", team: "Verona", era: "13/14", ovr: 78, roles: ["AS", "ES"] },
    { name: "E. Hallfredsson", team: "Verona", era: "13/14", ovr: 77, roles: ["CC", "ES"] },
    { name: "Rafael", team: "Verona", era: "13/14", ovr: 76, roles: ["POR"] },
    { name: "V. Moras", team: "Verona", era: "13/14", ovr: 76, roles: ["DC"] },
    { name: "D. Maietta", team: "Verona", era: "13/14", ovr: 75, roles: ["DC"] },
    { name: "F. Cacciatore", team: "Verona", era: "13/14", ovr: 75, roles: ["TD", "TS"] },
    { name: "A. Agostini", team: "Verona", era: "13/14", ovr: 74, roles: ["TS"] },
    { name: "D. Cacia", team: "Verona", era: "13/14", ovr: 74, roles: ["ATT"] },
    { name: "M. Donati", team: "Verona", era: "13/14", ovr: 73, roles: ["CC", "MED"] },
    { name: "Nicolas", team: "Verona", era: "13/14", ovr: 71, roles: ["POR"] },

    // FIORENTINA 2005/06 (Prandelli)
    { name: "L. Toni", team: "Fiorentina", era: "05/06", ovr: 88, roles: ["ATT"] },
    { name: "S. Frey", team: "Fiorentina", era: "05/06", ovr: 87, roles: ["POR"] },
    { name: "S. Fiore", team: "Fiorentina", era: "05/06", ovr: 84, roles: ["TRQ", "CC", "ED"] },
    { name: "T. Ujfalusi", team: "Fiorentina", era: "05/06", ovr: 84, roles: ["DC", "TD"] },
    { name: "M. Jorgensen", team: "Fiorentina", era: "05/06", ovr: 83, roles: ["ED", "AD", "TRQ"] },
    { name: "C. Brocchi", team: "Fiorentina", era: "05/06", ovr: 81, roles: ["MED", "CC"] },
    { name: "V. Bojinov", team: "Fiorentina", era: "05/06", ovr: 81, roles: ["ATT", "AS"] },
    { name: "D. Dainelli", team: "Fiorentina", era: "05/06", ovr: 80, roles: ["DC"] },
    { name: "M. Pasqual", team: "Fiorentina", era: "05/06", ovr: 80, roles: ["TS", "ES"] },
    { name: "G. Pazzini", team: "Fiorentina", era: "05/06", ovr: 80, roles: ["ATT"] },
    { name: "P. Kroldrup", team: "Fiorentina", era: "05/06", ovr: 79, roles: ["DC"] },
    { name: "M. Donadel", team: "Fiorentina", era: "05/06", ovr: 79, roles: ["CC", "MED"] },
    { name: "G. Pancaro", team: "Fiorentina", era: "05/06", ovr: 76, roles: ["TD", "TS"] },
    { name: "C. Lupatelli", team: "Fiorentina", era: "05/06", ovr: 75, roles: ["POR"] },

    // PIACENZA 2001/02 (Dario Hubner Capocannoniere)
    { name: "D. Hubner", team: "Piacenza", era: "01/02", ovr: 84, roles: ["ATT"] },
    { name: "C. Gautieri", team: "Piacenza", era: "01/02", ovr: 79, roles: ["ED", "AD"] },
    { name: "P. Poggi", team: "Piacenza", era: "01/02", ovr: 78, roles: ["ATT", "AS"] },
    { name: "Matuzalem", team: "Piacenza", era: "01/02", ovr: 78, roles: ["CC", "MED", "TRQ"] },
    { name: "S. Volpi", team: "Piacenza", era: "01/02", ovr: 77, roles: ["CC", "MED"] },
    { name: "A. Lucarelli", team: "Piacenza", era: "01/02", ovr: 76, roles: ["DC"] },
    { name: "M. Guardalben", team: "Piacenza", era: "01/02", ovr: 76, roles: ["POR"] },
    { name: "F. Statuto", team: "Piacenza", era: "01/02", ovr: 75, roles: ["CC", "MED"] },
    { name: "E. Di Francesco", team: "Piacenza", era: "01/02", ovr: 75, roles: ["CC", "ED"] },
    { name: "V. Tosto", team: "Piacenza", era: "01/02", ovr: 74, roles: ["TS", "ES"] },
    { name: "N. Mora", team: "Piacenza", era: "01/02", ovr: 74, roles: ["DC", "TD"] },
    { name: "V. Sommese", team: "Piacenza", era: "01/02", ovr: 73, roles: ["ES", "ED"] },
    { name: "L. Sacchetti", team: "Piacenza", era: "01/02", ovr: 73, roles: ["TD"] },
    { name: "N. Caccia", team: "Piacenza", era: "01/02", ovr: 73, roles: ["ATT"] },
    { name: "P. Orlandoni", team: "Piacenza", era: "01/02", ovr: 72, roles: ["POR"] },

    // SASSUOLO 2014/15 (Zaza, Berardi, Sansone)
    { name: "D. Berardi", team: "Sassuolo", era: "14/15", ovr: 84, roles: ["AD", "ATT"] },
    { name: "N. Sansone", team: "Sassuolo", era: "14/15", ovr: 82, roles: ["AS", "ES"] },
    { name: "S. Zaza", team: "Sassuolo", era: "14/15", ovr: 81, roles: ["ATT"] },
    { name: "F. Acerbi", team: "Sassuolo", era: "14/15", ovr: 81, roles: ["DC"] },
    { name: "S. Vrsaljko", team: "Sassuolo", era: "14/15", ovr: 80, roles: ["TD", "ED"] },
    { name: "A. Consigli", team: "Sassuolo", era: "14/15", ovr: 79, roles: ["POR"] },
    { name: "S. Missiroli", team: "Sassuolo", era: "14/15", ovr: 79, roles: ["CC", "TRQ"] },
    { name: "P. Cannavaro", team: "Sassuolo", era: "14/15", ovr: 78, roles: ["DC"] },
    { name: "F. Magnanelli", team: "Sassuolo", era: "14/15", ovr: 78, roles: ["CC", "MED"] },
    { name: "F. Peluso", team: "Sassuolo", era: "14/15", ovr: 77, roles: ["TS", "DC"] },
    { name: "S. Taider", team: "Sassuolo", era: "14/15", ovr: 77, roles: ["CC", "MED"] },
    { name: "D. Biondini", team: "Sassuolo", era: "14/15", ovr: 76, roles: ["CC", "MED"] },
    { name: "A. Floro Flores", team: "Sassuolo", era: "14/15", ovr: 75, roles: ["ATT", "AS"] },
    { name: "S. Floccari", team: "Sassuolo", era: "14/15", ovr: 75, roles: ["ATT"] },
    { name: "A. Pomini", team: "Sassuolo", era: "14/15", ovr: 73, roles: ["POR"] },
    // --- BLOCCO 4: BANTER ERA, MEME SQUAD E ERA MODERNA (2020+) ---

    // MILAN BANTER ERA (2014/15 - Inzaghi)
    { name: "J. Menez", team: "Milan", era: "Banter Era 14/15", ovr: 82, roles: ["ATT", "TRQ", "AS"] },
    { name: "G. Bonaventura", team: "Milan", era: "Banter Era 14/15", ovr: 80, roles: ["ES", "CC", "TRQ"] },
    { name: "Diego Lopez", team: "Milan", era: "Banter Era 14/15", ovr: 81, roles: ["POR"] },
    { name: "N. De Jong", team: "Milan", era: "Banter Era 14/15", ovr: 79, roles: ["MED", "CC"] },
    { name: "K. Honda", team: "Milan", era: "Banter Era 14/15", ovr: 77, roles: ["TRQ", "ED", "AD"] },
    { name: "I. Abate", team: "Milan", era: "Banter Era 14/15", ovr: 76, roles: ["TD", "ED"] },
    { name: "P. Mexes", team: "Milan", era: "Banter Era 14/15", ovr: 76, roles: ["DC"] },
    { name: "A. Rami", team: "Milan", era: "Banter Era 14/15", ovr: 75, roles: ["DC"] },
    { name: "A. Poli", team: "Milan", era: "Banter Era 14/15", ovr: 74, roles: ["CC", "MED", "TD"] },
    { name: "M. De Sciglio", team: "Milan", era: "Banter Era 14/15", ovr: 73, roles: ["TD", "TS"] },
    { name: "S. Muntari", team: "Milan", era: "Banter Era 14/15", ovr: 73, roles: ["MED", "CC"] },
    { name: "M. Essien", team: "Milan", era: "Banter Era 14/15", ovr: 72, roles: ["MED", "CC"] },
    { name: "M. Niang", team: "Milan", era: "Banter Era 14/15", ovr: 73, roles: ["AD", "ATT"] },
    { name: "A. Cerci", team: "Milan", era: "Banter Era 14/15", ovr: 75, roles: ["AD", "ED"] },
    { name: "M. Destro", team: "Milan", era: "Banter Era 14/15", ovr: 75, roles: ["ATT"] },

    // INTER BANTER ERA (2014/15 - Mazzarri/Mancini)
    { name: "M. Icardi", team: "Inter", era: "Banter Era 14/15", ovr: 83, roles: ["ATT"] },
    { name: "S. Handanovic", team: "Inter", era: "Banter Era 14/15", ovr: 83, roles: ["POR"] },
    { name: "M. Kovacic", team: "Inter", era: "Banter Era 14/15", ovr: 80, roles: ["TRQ", "CC"] },
    { name: "R. Palacio", team: "Inter", era: "Banter Era 14/15", ovr: 79, roles: ["ATT", "AS", "AD"] },
    { name: "F. Guarin", team: "Inter", era: "Banter Era 14/15", ovr: 78, roles: ["CC", "TRQ", "MED"] },
    { name: "N. Vidic", team: "Inter", era: "Banter Era 14/15", ovr: 77, roles: ["DC"] },
    { name: "G. Medel", team: "Inter", era: "Banter Era 14/15", ovr: 77, roles: ["MED", "DC"] },
    { name: "Juan Jesus", team: "Inter", era: "Banter Era 14/15", ovr: 75, roles: ["DC", "TS"] },
    { name: "A. Ranocchia", team: "Inter", era: "Banter Era 14/15", ovr: 75, roles: ["DC"] },
    { name: "Y. Nagatomo", team: "Inter", era: "Banter Era 14/15", ovr: 74, roles: ["TS", "TD", "ES"] },
    { name: "H. Campagnaro", team: "Inter", era: "Banter Era 14/15", ovr: 74, roles: ["DC", "TD"] },
    { name: "Dodô", team: "Inter", era: "Banter Era 14/15", ovr: 73, roles: ["TS", "ES"] },
    { name: "Z. Kuzmanovic", team: "Inter", era: "Banter Era 14/15", ovr: 72, roles: ["CC", "MED"] },
    { name: "Jonathan", team: "Inter", era: "Banter Era 14/15", ovr: 72, roles: ["TD", "ED"] },
    { name: "P. Osvaldo", team: "Inter", era: "Banter Era 14/15", ovr: 76, roles: ["ATT"] },

    // JUVENTUS BANTER ERA (2009/10 - Ferrara/Zaccheroni)
    { name: "G. Buffon", team: "Juventus", era: "Banter 09/10", ovr: 86, roles: ["POR"] },
    { name: "G. Chiellini", team: "Juventus", era: "Banter 09/10", ovr: 85, roles: ["DC", "TS"] },
    { name: "Diego", team: "Juventus", era: "Banter 09/10", ovr: 83, roles: ["TRQ"] },
    { name: "Felipe Melo", team: "Juventus", era: "Banter 09/10", ovr: 80, roles: ["MED", "CC"] },
    { name: "M. Sissoko", team: "Juventus", era: "Banter 09/10", ovr: 80, roles: ["MED", "CC"] },
    { name: "C. Marchisio", team: "Juventus", era: "Banter 09/10", ovr: 80, roles: ["CC", "MED"] },
    { name: "Amauri", team: "Juventus", era: "Banter 09/10", ovr: 79, roles: ["ATT"] },
    { name: "V. Iaquinta", team: "Juventus", era: "Banter 09/10", ovr: 79, roles: ["ATT", "AD"] },
    { name: "F. Cannavaro", team: "Juventus", era: "Banter 09/10", ovr: 78, roles: ["DC"] },
    { name: "N. Legrottaglie", team: "Juventus", era: "Banter 09/10", ovr: 77, roles: ["DC"] },
    { name: "F. Grosso", team: "Juventus", era: "Banter 09/10", ovr: 76, roles: ["TS"] },
    { name: "Z. Grygera", team: "Juventus", era: "Banter 09/10", ovr: 75, roles: ["TD", "DC"] },
    { name: "C. Poulsen", team: "Juventus", era: "Banter 09/10", ovr: 74, roles: ["MED", "CC"] },
    { name: "J. Zebina", team: "Juventus", era: "Banter 09/10", ovr: 73, roles: ["TD"] },
    { name: "A. Manninger", team: "Juventus", era: "Banter 09/10", ovr: 75, roles: ["POR"] },

    // ROMA "MEME & DELUSIONI" (Mix 2015-2018 Iturbe, Schick, Doumbia)
    { name: "R. Nainggolan", team: "Roma", era: "Meme/Monchi Mix", ovr: 86, roles: ["CC", "TRQ", "MED"] },
    { name: "E. Dzeko", team: "Roma", era: "Meme/Monchi Mix", ovr: 85, roles: ["ATT"] },
    { name: "Alisson", team: "Roma", era: "Meme/Monchi Mix", ovr: 85, roles: ["POR"] },
    { name: "P. Schick", team: "Roma", era: "Meme/Monchi Mix", ovr: 76, roles: ["ATT", "AD"] },
    { name: "J. Iturbe", team: "Roma", era: "Meme/Monchi Mix", ovr: 74, roles: ["AD", "AS"] },
    { name: "S. Doumbia", team: "Roma", era: "Meme/Monchi Mix", ovr: 75, roles: ["ATT"] },
    { name: "V. Ibarbo", team: "Roma", era: "Meme/Monchi Mix", ovr: 75, roles: ["AD", "ATT"] },
    { name: "M. Gonalons", team: "Roma", era: "Meme/Monchi Mix", ovr: 74, roles: ["MED", "CC"] },
    { name: "H. Moreno", team: "Roma", era: "Meme/Monchi Mix", ovr: 74, roles: ["DC", "TS"] },
    { name: "Bruno Peres", team: "Roma", era: "Meme/Monchi Mix", ovr: 75, roles: ["TD", "ED"] },
    { name: "G. Defrel", team: "Roma", era: "Meme/Monchi Mix", ovr: 75, roles: ["ATT", "AD"] },
    { name: "R. Olsen", team: "Roma", era: "Meme/Monchi Mix", ovr: 76, roles: ["POR"] },
    { name: "W. Bianda", team: "Roma", era: "Meme/Monchi Mix", ovr: 65, roles: ["DC"] },
    { name: "A. Coric", team: "Roma", era: "Meme/Monchi Mix", ovr: 68, roles: ["CC", "TRQ"] },

    // NAPOLI SCUDETTO (2022/23 - Spalletti)
    { name: "K. Kvaratskhelia", team: "Napoli", era: "22/23", ovr: 88, roles: ["AS", "ATT", "TRQ"] },
    { name: "V. Osimhen", team: "Napoli", era: "22/23", ovr: 88, roles: ["ATT"] },
    { name: "Kim Min-jae", team: "Napoli", era: "22/23", ovr: 86, roles: ["DC"] },
    { name: "S. Lobotka", team: "Napoli", era: "22/23", ovr: 85, roles: ["MED", "CC"] },
    { name: "G. Di Lorenzo", team: "Napoli", era: "22/23", ovr: 85, roles: ["TD", "ED"] },
    { name: "P. Zielinski", team: "Napoli", era: "22/23", ovr: 84, roles: ["CC", "TRQ"] },
    { name: "A. Zambo Anguissa", team: "Napoli", era: "22/23", ovr: 84, roles: ["CC", "MED"] },
    { name: "A. Meret", team: "Napoli", era: "22/23", ovr: 82, roles: ["POR"] },
    { name: "A. Rrahmani", team: "Napoli", era: "22/23", ovr: 82, roles: ["DC"] },
    { name: "Mario Rui", team: "Napoli", era: "22/23", ovr: 80, roles: ["TS", "ES"] },
    { name: "M. Politano", team: "Napoli", era: "22/23", ovr: 80, roles: ["AD", "ED"] },
    { name: "H. Lozano", team: "Napoli", era: "22/23", ovr: 80, roles: ["AD", "AS"] },
    { name: "E. Elmas", team: "Napoli", era: "22/23", ovr: 79, roles: ["CC", "TRQ", "ES"] },
    { name: "G. Simeone", team: "Napoli", era: "22/23", ovr: 79, roles: ["ATT"] },
    { name: "G. Raspadori", team: "Napoli", era: "22/23", ovr: 78, roles: ["ATT", "TRQ", "AS"] },

    // MILAN SCUDETTO (2021/22 - Pioli)
    { name: "R. Leao", team: "Milan", era: "21/22", ovr: 86, roles: ["AS", "ATT"] },
    { name: "M. Maignan", team: "Milan", era: "21/22", ovr: 87, roles: ["POR"] },
    { name: "T. Hernandez", team: "Milan", era: "21/22", ovr: 86, roles: ["TS", "ES"] },
    { name: "S. Tonali", team: "Milan", era: "21/22", ovr: 84, roles: ["CC", "MED"] },
    { name: "F. Kessie", team: "Milan", era: "21/22", ovr: 84, roles: ["MED", "CC"] },
    { name: "F. Tomori", team: "Milan", era: "21/22", ovr: 84, roles: ["DC"] },
    { name: "O. Giroud", team: "Milan", era: "21/22", ovr: 83, roles: ["ATT"] },
    { name: "P. Kalulu", team: "Milan", era: "21/22", ovr: 81, roles: ["DC", "TD"] },
    { name: "I. Bennacer", team: "Milan", era: "21/22", ovr: 81, roles: ["MED", "CC"] },
    { name: "S. Kjaer", team: "Milan", era: "21/22", ovr: 81, roles: ["DC"] },
    { name: "D. Calabria", team: "Milan", era: "21/22", ovr: 80, roles: ["TD"] },
    { name: "A. Romagnoli", team: "Milan", era: "21/22", ovr: 79, roles: ["DC"] },
    { name: "Brahim Diaz", team: "Milan", era: "21/22", ovr: 79, roles: ["TRQ", "AD"] },
    { name: "A. Saelemaekers", team: "Milan", era: "21/22", ovr: 78, roles: ["ED", "AD"] },
    { name: "J. Messias", team: "Milan", era: "21/22", ovr: 77, roles: ["ED", "AD", "TRQ"] },
    { name: "C. Tatarusanu", team: "Milan", era: "21/22", ovr: 75, roles: ["POR"] },

    // INTER SECONDA STELLA (2023/24 - Inzaghi)
    { name: "L. Martinez", team: "Inter", era: "23/24", ovr: 89, roles: ["ATT"] },
    { name: "N. Barella", team: "Inter", era: "23/24", ovr: 88, roles: ["CC"] },
    { name: "H. Calhanoglu", team: "Inter", era: "23/24", ovr: 88, roles: ["MED", "CC"] },
    { name: "A. Bastoni", team: "Inter", era: "23/24", ovr: 87, roles: ["DC", "TS"] },
    { name: "F. Dimarco", team: "Inter", era: "23/24", ovr: 86, roles: ["ES", "TS"] },
    { name: "M. Thuram", team: "Inter", era: "23/24", ovr: 85, roles: ["ATT", "AS"] },
    { name: "Y. Sommer", team: "Inter", era: "23/24", ovr: 85, roles: ["POR"] },
    { name: "H. Mkhitaryan", team: "Inter", era: "23/24", ovr: 84, roles: ["CC", "TRQ"] },
    { name: "B. Pavard", team: "Inter", era: "23/24", ovr: 84, roles: ["DC", "TD"] },
    { name: "F. Acerbi", team: "Inter", era: "23/24", ovr: 83, roles: ["DC"] },
    { name: "D. Dumfries", team: "Inter", era: "23/24", ovr: 81, roles: ["ED", "TD"] },
    { name: "D. Frattesi", team: "Inter", era: "23/24", ovr: 81, roles: ["CC"] },
    { name: "S. De Vrij", team: "Inter", era: "23/24", ovr: 81, roles: ["DC"] },
    { name: "M. Darmian", team: "Inter", era: "23/24", ovr: 80, roles: ["ED", "TD", "DC"] },
    { name: "Carlos Augusto", team: "Inter", era: "23/24", ovr: 79, roles: ["ES", "TS", "DC"] },

    // BOLOGNA CHAMPIONS LEAGUE (2023/24 - Thiago Motta)
    { name: "J. Zirkzee", team: "Bologna", era: "23/24", ovr: 83, roles: ["ATT", "TRQ"] },
    { name: "L. Ferguson", team: "Bologna", era: "23/24", ovr: 82, roles: ["CC", "TRQ"] },
    { name: "R. Calafiori", team: "Bologna", era: "23/24", ovr: 81, roles: ["DC", "TS"] },
    { name: "R. Orsolini", team: "Bologna", era: "23/24", ovr: 81, roles: ["AD", "ED"] },
    { name: "R. Freuler", team: "Bologna", era: "23/24", ovr: 80, roles: ["MED", "CC"] },
    { name: "L. Skorupski", team: "Bologna", era: "23/24", ovr: 80, roles: ["POR"] },
    { name: "S. Beukema", team: "Bologna", era: "23/24", ovr: 79, roles: ["DC"] },
    { name: "D. Ndoye", team: "Bologna", era: "23/24", ovr: 79, roles: ["AD", "AS", "ED", "ES"] },
    { name: "S. Posch", team: "Bologna", era: "23/24", ovr: 78, roles: ["TD", "DC"] },
    { name: "A. Saelemaekers", team: "Bologna", era: "23/24", ovr: 78, roles: ["AS", "AD", "ES", "ED"] },
    { name: "J. Lucumi", team: "Bologna", era: "23/24", ovr: 78, roles: ["DC"] },
    { name: "M. Aebischer", team: "Bologna", era: "23/24", ovr: 77, roles: ["CC", "MED"] },
    { name: "V. Kristiansen", team: "Bologna", era: "23/24", ovr: 77, roles: ["TS"] },
    { name: "G. Fabbian", team: "Bologna", era: "23/24", ovr: 76, roles: ["CC", "TRQ"] },

    // PALERMO DEI GIOIELLI (2014/15 - Iachini)
    { name: "P. Dybala", team: "Palermo", era: "14/15", ovr: 83, roles: ["ATT", "TRQ"] },
    { name: "F. Vazquez", team: "Palermo", era: "14/15", ovr: 81, roles: ["TRQ", "ATT", "CC"] },
    { name: "E. Barreto", team: "Palermo", era: "14/15", ovr: 78, roles: ["CC", "MED"] },
    { name: "S. Sorrentino", team: "Palermo", era: "14/15", ovr: 78, roles: ["POR"] },
    { name: "A. Belotti", team: "Palermo", era: "14/15", ovr: 77, roles: ["ATT"] },
    { name: "L. Rigoni", team: "Palermo", era: "14/15", ovr: 76, roles: ["CC", "MED"] },
    { name: "G. Gonzalez", team: "Palermo", era: "14/15", ovr: 76, roles: ["DC"] },
    { name: "E. Munoz", team: "Palermo", era: "14/15", ovr: 75, roles: ["DC"] },
    { name: "A. Lazaar", team: "Palermo", era: "14/15", ovr: 75, roles: ["TS", "ES"] },
    { name: "S. Andelkovic", team: "Palermo", era: "14/15", ovr: 74, roles: ["DC"] },
    { name: "E. Maresca", team: "Palermo", era: "14/15", ovr: 74, roles: ["MED", "CC"] },
    { name: "I. Chochev", team: "Palermo", era: "14/15", ovr: 73, roles: ["CC"] },
    { name: "M. Morganella", team: "Palermo", era: "14/15", ovr: 73, roles: ["TD", "ED"] },

    // MONZA (2022/23 - Palladino)
    { name: "M. Pessina", team: "Monza", era: "22/23", ovr: 79, roles: ["CC", "TRQ", "MED"] },
    { name: "Carlos Augusto", team: "Monza", era: "22/23", ovr: 78, roles: ["TS", "ES"] },
    { name: "M. Di Gregorio", team: "Monza", era: "22/23", ovr: 78, roles: ["POR"] },
    { name: "P. Ciurria", team: "Monza", era: "22/23", ovr: 77, roles: ["ED", "AD", "TRQ"] },
    { name: "G. Caprari", team: "Monza", era: "22/23", ovr: 77, roles: ["TRQ", "AS", "ATT"] },
    { name: "D. Mota", team: "Monza", era: "22/23", ovr: 76, roles: ["ATT", "AS"] },
    { name: "A. Izzo", team: "Monza", era: "22/23", ovr: 76, roles: ["DC", "TD"] },
    { name: "P. Marí", team: "Monza", era: "22/23", ovr: 76, roles: ["DC"] },
    { name: "N. Rovella", team: "Monza", era: "22/23", ovr: 76, roles: ["MED", "CC"] },
    { name: "S. Sensi", team: "Monza", era: "22/23", ovr: 75, roles: ["CC", "TRQ"] },
    { name: "M. Caldirola", team: "Monza", era: "22/23", ovr: 74, roles: ["DC"] },
    { name: "A. Petagna", team: "Monza", era: "22/23", ovr: 75, roles: ["ATT"] },
    // --- BLOCCO 5 E 6: SQUADRE MEME E RIVELAZIONI RECENTI ---

    // COMO 2024/25 (La Hollywood del Lario di Fabregas)
    { name: "N. Paz", team: "Como", era: "24/25", ovr: 81, roles: ["TRQ", "CC", "AD"] },
    { name: "P. Cutrone", team: "Como", era: "24/25", ovr: 79, roles: ["ATT"] },
    { name: "S. Roberto", team: "Como", era: "24/25", ovr: 78, roles: ["CC", "MED", "TD"] },
    { name: "G. Strefezza", team: "Como", era: "24/25", ovr: 78, roles: ["AD", "AS", "TRQ"] },
    { name: "M. Perrone", team: "Como", era: "24/25", ovr: 77, roles: ["CC", "MED"] },
    { name: "A. Belotti", team: "Como", era: "24/25", ovr: 77, roles: ["ATT"] },
    { name: "A. Dossena", team: "Como", era: "24/25", ovr: 76, roles: ["DC"] },
    { name: "E. Audero", team: "Como", era: "24/25", ovr: 76, roles: ["POR"] },
    { name: "A. Fadera", team: "Como", era: "24/25", ovr: 75, roles: ["AS", "ES"] },
    { name: "A. Moreno", team: "Como", era: "24/25", ovr: 75, roles: ["TS", "ES"] },
    { name: "L. Mazzitelli", team: "Como", era: "24/25", ovr: 75, roles: ["CC", "MED"] },
    { name: "M. Kempf", team: "Como", era: "24/25", ovr: 74, roles: ["DC"] },
    { name: "P. Reina", team: "Como", era: "24/25", ovr: 74, roles: ["POR"] },
    { name: "L. Da Cunha", team: "Como", era: "24/25", ovr: 73, roles: ["TRQ", "AD"] },

    // GENOA 2023/24 (La Rivelazione di Gilardino)
    { name: "A. Gudmundsson", team: "Genoa", era: "23/24", ovr: 84, roles: ["ATT", "TRQ", "AS"] },
    { name: "M. Retegui", team: "Genoa", era: "23/24", ovr: 82, roles: ["ATT"] },
    { name: "J. Martinez", team: "Genoa", era: "23/24", ovr: 81, roles: ["POR"] },
    { name: "M. Frendrup", team: "Genoa", era: "23/24", ovr: 80, roles: ["CC", "MED", "TD"] },
    { name: "R. Malinovskyi", team: "Genoa", era: "23/24", ovr: 79, roles: ["TRQ", "CC"] },
    { name: "R. Dragusin", team: "Genoa", era: "23/24", ovr: 79, roles: ["DC"] },
    { name: "J. Vasquez", team: "Genoa", era: "23/24", ovr: 78, roles: ["DC", "TS"] },
    { name: "K. Strootman", team: "Genoa", era: "23/24", ovr: 77, roles: ["CC", "MED"] },
    { name: "A. Martin", team: "Genoa", era: "23/24", ovr: 76, roles: ["TS", "ES"] },
    { name: "M. Bani", team: "Genoa", era: "23/24", ovr: 76, roles: ["DC"] },
    { name: "S. Sabelli", team: "Genoa", era: "23/24", ovr: 75, roles: ["TD", "ED"] },
    { name: "C. Ekuban", team: "Genoa", era: "23/24", ovr: 74, roles: ["ATT", "AD"] },

    // SASSUOLO 2020/21 (Il picco del DeZerbisimo)
    { name: "D. Berardi", team: "Sassuolo", era: "20/21", ovr: 86, roles: ["AD", "ATT"] },
    { name: "M. Locatelli", team: "Sassuolo", era: "20/21", ovr: 84, roles: ["CC", "MED"] },
    { name: "J. Boga", team: "Sassuolo", era: "20/21", ovr: 83, roles: ["AS", "ES"] },
    { name: "G. Raspadori", team: "Sassuolo", era: "20/21", ovr: 81, roles: ["ATT", "TRQ"] },
    { name: "F. Caputo", team: "Sassuolo", era: "20/21", ovr: 81, roles: ["ATT"] },
    { name: "F. Djuricic", team: "Sassuolo", era: "20/21", ovr: 80, roles: ["TRQ", "AS"] },
    { name: "M. Lopez", team: "Sassuolo", era: "20/21", ovr: 80, roles: ["MED", "CC"] },
    { name: "G. Ferrari", team: "Sassuolo", era: "20/21", ovr: 79, roles: ["DC"] },
    { name: "A. Consigli", team: "Sassuolo", era: "20/21", ovr: 80, roles: ["POR"] },
    { name: "Rogerio", team: "Sassuolo", era: "20/21", ovr: 77, roles: ["TS"] },
    { name: "M. Muldur", team: "Sassuolo", era: "20/21", ovr: 77, roles: ["TD"] },
    { name: "V. Chiriches", team: "Sassuolo", era: "20/21", ovr: 76, roles: ["DC"] },

    // ANCONA 2003/04 (La Meme Squad Definitiva - 13 Punti in A)
    { name: "M. Jardel", team: "Ancona", era: "Meme 03/04", ovr: 73, roles: ["ATT"] },
    { name: "D. Hubner", team: "Ancona", era: "Meme 03/04", ovr: 74, roles: ["ATT"] },
    { name: "M. Ganz", team: "Ancona", era: "Meme 03/04", ovr: 72, roles: ["ATT"] },
    { name: "M. Milanese", team: "Ancona", era: "Meme 03/04", ovr: 73, roles: ["TS", "ES"] },
    { name: "D. Andersson", team: "Ancona", era: "Meme 03/04", ovr: 73, roles: ["CC", "MED"] },
    { name: "G. Maini", team: "Ancona", era: "Meme 03/04", ovr: 71, roles: ["CC"] },
    { name: "A. Scarpi", team: "Ancona", era: "Meme 03/04", ovr: 71, roles: ["POR"] },
    { name: "S. Marcon", team: "Ancona", era: "Meme 03/04", ovr: 68, roles: ["POR"] },
    { name: "E. Baccin", team: "Ancona", era: "Meme 03/04", ovr: 70, roles: ["DC", "TD"] },
    { name: "C. Bucchi", team: "Ancona", era: "Meme 03/04", ovr: 72, roles: ["ATT"] },
    { name: "P. Poggi", team: "Ancona", era: "Meme 03/04", ovr: 71, roles: ["ATT", "AS"] },
    { name: "L. Bilica", team: "Ancona", era: "Meme 03/04", ovr: 70, roles: ["DC"] },

    // PESCARA 2012/13 (Zemanlandia mancata e disastri in difesa)
    { name: "J. Quintero", team: "Pescara", era: "Meme 12/13", ovr: 77, roles: ["TRQ", "CC"] },
    { name: "M. Perin", team: "Pescara", era: "Meme 12/13", ovr: 76, roles: ["POR"] },
    { name: "V. Weiss", team: "Pescara", era: "Meme 12/13", ovr: 76, roles: ["AS", "TRQ", "ED"] },
    { name: "G. D'Agostino", team: "Pescara", era: "Meme 12/13", ovr: 74, roles: ["CC", "MED"] },
    { name: "G. Caprari", team: "Pescara", era: "Meme 12/13", ovr: 74, roles: ["AS", "AD", "ATT"] },
    { name: "B. Bjarnason", team: "Pescara", era: "Meme 12/13", ovr: 73, roles: ["CC", "ES", "ED"] },
    { name: "E. Abbruscato", team: "Pescara", era: "Meme 12/13", ovr: 72, roles: ["ATT"] },
    { name: "M. Cascione", team: "Pescara", era: "Meme 12/13", ovr: 72, roles: ["CC", "MED"] },
    { name: "D. Zanon", team: "Pescara", era: "Meme 12/13", ovr: 71, roles: ["TD"] },
    { name: "U. Cosic", team: "Pescara", era: "Meme 12/13", ovr: 70, roles: ["DC"] },
    { name: "I. Pelizzoli", team: "Pescara", era: "Meme 12/13", ovr: 71, roles: ["POR"] },
    { name: "M. Vukusic", team: "Pescara", era: "Meme 12/13", ovr: 71, roles: ["ATT"] },

    // SALERNITANA 2021/22 (Il Miracolo 7% di Davide Nicola)
    { name: "F. Ribery", team: "Salernitana", era: "Miracolo 21/22", ovr: 79, roles: ["TRQ", "AS", "ATT"] },
    { name: "Ederson", team: "Salernitana", era: "Miracolo 21/22", ovr: 79, roles: ["CC", "MED", "TRQ"] },
    { name: "S. Verdi", team: "Salernitana", era: "Miracolo 21/22", ovr: 78, roles: ["TRQ", "AS", "AD"] },
    { name: "M. Djuric", team: "Salernitana", era: "Miracolo 21/22", ovr: 77, roles: ["ATT"] },
    { name: "F. Bonazzoli", team: "Salernitana", era: "Miracolo 21/22", ovr: 77, roles: ["ATT"] },
    { name: "P. Mazzocchi", team: "Salernitana", era: "Miracolo 21/22", ovr: 76, roles: ["TD", "TS", "ED"] },
    { name: "L. Sepe", team: "Salernitana", era: "Miracolo 21/22", ovr: 76, roles: ["POR"] },
    { name: "I. Radovanovic", team: "Salernitana", era: "Miracolo 21/22", ovr: 75, roles: ["DC", "MED"] },
    { name: "F. Fazio", team: "Salernitana", era: "Miracolo 21/22", ovr: 75, roles: ["DC"] },
    { name: "L. Coulibaly", team: "Salernitana", era: "Miracolo 21/22", ovr: 75, roles: ["CC", "MED"] },
    { name: "N. Gyomber", team: "Salernitana", era: "Miracolo 21/22", ovr: 74, roles: ["DC"] },
    { name: "G. Kastanos", team: "Salernitana", era: "Miracolo 21/22", ovr: 74, roles: ["CC", "TRQ", "ED"] },

    // CARPI 2015/16 (La favola di Castori)
    { name: "K. Lasagna", team: "Carpi", era: "15/16", ovr: 76, roles: ["ATT"] },
    { name: "J. Mbakogu", team: "Carpi", era: "15/16", ovr: 75, roles: ["ATT"] },
    { name: "L. Lollo", team: "Carpi", era: "15/16", ovr: 74, roles: ["CC", "MED", "TRQ"] },
    { name: "G. Letizia", team: "Carpi", era: "15/16", ovr: 75, roles: ["TD", "TS", "ED"] },
    { name: "R. Gagliolo", team: "Carpi", era: "15/16", ovr: 75, roles: ["DC", "TS"] },
    { name: "V. Belec", team: "Carpi", era: "15/16", ovr: 74, roles: ["POR"] },
    { name: "S. Romagnoli", team: "Carpi", era: "15/16", ovr: 74, roles: ["DC"] },
    { name: "R. Bianco", team: "Carpi", era: "15/16", ovr: 73, roles: ["CC", "MED"] },
    { name: "I. Cofie", team: "Carpi", era: "15/16", ovr: 73, roles: ["CC", "MED"] },
    { name: "A. Di Gaudio", team: "Carpi", era: "15/16", ovr: 73, roles: ["AS", "ED"] },
    { name: "C. Zaccardo", team: "Carpi", era: "15/16", ovr: 74, roles: ["DC", "TD"] }
];